version: "3"

services:
  wanbot:
    build:
      context .
      dockerfile: Dockerfile
    image: domhauton/wanbot
    mem_limit: 256m
    ports:
      - "5000:80"
    environment:
      - BITLY_USER=${BITLY_USER}
      - BITLY_PASS=${BITLY_PASS}
      - TWITCH_USER=${TWITCH_USER}
      - TWITCH_PASS=${TWITCH_PASS}