version: "3"

services:
  wanbot:
    build:
      context .
      dockerfile: Dockerfile
    image: domhauton/wanbot
    mem_limit: 256m
    ports:
      - "5000:80"
    environment:
      - WANBOT_TWITCH_USERS=${WANBOT_TWITCH_USERS}
      - WANBOT_TWITCH_OAUTH=${WANBOT_TWITCH_OAUTH}
      - WANBOT_BITLY_USER=${WANBOT_BITLY_USER}
      - WANBOT_BITLY_TOKEN=${WANBOT_BITLY_TOKEN}
    volumes:
      - ~/.config/wanbot.yml:/config/wanbot.yml